//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContagemAssistencia.ABC_Translate {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContagemAssistencia.ABC_Translate.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ok.
        /// </summary>
        internal static string AlerAttentiontDeleteAnswerFalse {
            get {
                return ResourceManager.GetString("AlerAttentiontDeleteAnswerFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Add.
        /// </summary>
        internal static string AlertAttentionDeleteAnswerTrue {
            get {
                return ResourceManager.GetString("AlertAttentionDeleteAnswerTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a There is no attendance yet, please add a NEW PARTICIPANT.
        /// </summary>
        internal static string AlertAttentionDeleteMessage {
            get {
                return ResourceManager.GetString("AlertAttentionDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ok.
        /// </summary>
        internal static string AlertAttentionNMAnswer {
            get {
                return ResourceManager.GetString("AlertAttentionNMAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please check if you entered a number greater than zero and that the field is not empty.
        /// </summary>
        internal static string AlertAttentionNMMenssage {
            get {
                return ResourceManager.GetString("AlertAttentionNMMenssage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No.
        /// </summary>
        internal static string AlertDeleteAnswerFalse {
            get {
                return ResourceManager.GetString("AlertDeleteAnswerFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Yes.
        /// </summary>
        internal static string AlertDeleteAnswerTrue {
            get {
                return ResourceManager.GetString("AlertDeleteAnswerTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Do you want to delete this attendance?.
        /// </summary>
        internal static string AlertDeleteMessage {
            get {
                return ResourceManager.GetString("AlertDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Attention.
        /// </summary>
        internal static string AlertTitleAttentionDelete {
            get {
                return ResourceManager.GetString("AlertTitleAttentionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Attention.
        /// </summary>
        internal static string AlertTitleAttentionNM {
            get {
                return ResourceManager.GetString("AlertTitleAttentionNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aquatic theme.
        /// </summary>
        internal static string Aquatic_theme {
            get {
                return ResourceManager.GetString("Aquatic theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ATTENDANCE.
        /// </summary>
        internal static string Assists {
            get {
                return ResourceManager.GetString("Assists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ADD.
        /// </summary>
        internal static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NEW PARTICIPANT.
        /// </summary>
        internal static string BtnNewAssistance {
            get {
                return ResourceManager.GetString("BtnNewAssistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SHARE ATTENDANCE.
        /// </summary>
        internal static string BtnShareAssistance {
            get {
                return ResourceManager.GetString("BtnShareAssistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a VISUALIZE.
        /// </summary>
        internal static string BtnVisualize {
            get {
                return ResourceManager.GetString("BtnVisualize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Choose theme.
        /// </summary>
        internal static string Choose_theme {
            get {
                return ResourceManager.GetString("Choose theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dark theme.
        /// </summary>
        internal static string Dark_theme {
            get {
                return ResourceManager.GetString("Dark theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Default theme.
        /// </summary>
        internal static string Default_theme {
            get {
                return ResourceManager.GetString("Default theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Edit Theme.
        /// </summary>
        internal static string EditTheme {
            get {
                return ResourceManager.GetString("EditTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fire theme.
        /// </summary>
        internal static string Fire_theme {
            get {
                return ResourceManager.GetString("Fire theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lemon theme.
        /// </summary>
        internal static string Lemon_theme {
            get {
                return ResourceManager.GetString("Lemon theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Number.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enter the Name Here.
        /// </summary>
        internal static string PHname {
            get {
                return ResourceManager.GetString("PHname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enter the Number Here.
        /// </summary>
        internal static string PHnumber {
            get {
                return ResourceManager.GetString("PHnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Add.
        /// </summary>
        internal static string TitleAdd {
            get {
                return ResourceManager.GetString("TitleAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Attendance.
        /// </summary>
        internal static string TitleAssists {
            get {
                return ResourceManager.GetString("TitleAssists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Share Attendance.
        /// </summary>
        internal static string TitleShare {
            get {
                return ResourceManager.GetString("TitleShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Visualize.
        /// </summary>
        internal static string TitleVisualize {
            get {
                return ResourceManager.GetString("TitleVisualize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Total =.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
    }
}
